// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MobID.MainGateway.Repo;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MobID.MainGateway.Migrations
{
    [DbContext(typeof(MainDbContext))]
    partial class MainDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MobID.MainGateway.Models.Entities.Access", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccessTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpirationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRestrictedToOrgMembers")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRestrictedToOrganizationShare")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan?>("SubscriptionPeriod")
                        .HasColumnType("interval");

                    b.Property<int?>("TotalUseLimit")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UseLimitPerPeriod")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccessTypeId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Accesses");
                });

            modelBuilder.Entity("MobID.MainGateway.Models.Entities.AccessType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsLimitedUse")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSubscription")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AccessTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaa0001"),
                            CreatedAt = new DateTime(2025, 5, 25, 23, 56, 19, 806, DateTimeKind.Utc).AddTicks(7592),
                            Description = "Acces cu limită totală de utilizări",
                            IsLimitedUse = true,
                            IsSubscription = false,
                            Name = "LimitedUse",
                            UpdatedAt = new DateTime(2025, 5, 25, 23, 56, 19, 806, DateTimeKind.Utc).AddTicks(7593)
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaa0002"),
                            CreatedAt = new DateTime(2025, 5, 25, 23, 56, 19, 806, DateTimeKind.Utc).AddTicks(7597),
                            Description = "Acces în abonament pe perioade",
                            IsLimitedUse = false,
                            IsSubscription = true,
                            Name = "Subscription",
                            UpdatedAt = new DateTime(2025, 5, 25, 23, 56, 19, 806, DateTimeKind.Utc).AddTicks(7597)
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaa0003"),
                            CreatedAt = new DateTime(2025, 5, 25, 23, 56, 19, 806, DateTimeKind.Utc).AddTicks(7601),
                            Description = "Confirmare unică de identitate per utilizator",
                            IsLimitedUse = false,
                            IsSubscription = false,
                            Name = "IdentityConfirm",
                            UpdatedAt = new DateTime(2025, 5, 25, 23, 56, 19, 806, DateTimeKind.Utc).AddTicks(7602)
                        });
                });

            modelBuilder.Entity("MobID.MainGateway.Models.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("MobID.MainGateway.Models.Entities.OrganizationAccessShare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccessId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SourceOrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetOrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccessId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("SourceOrganizationId");

                    b.HasIndex("TargetOrganizationId");

                    b.ToTable("OrganizationAccessShares");
                });

            modelBuilder.Entity("MobID.MainGateway.Models.Entities.OrganizationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("UserId");

                    b.ToTable("OrganizationUsers");
                });

            modelBuilder.Entity("MobID.MainGateway.Models.Entities.QrCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccessId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccessId");

                    b.ToTable("QrCodes");
                });

            modelBuilder.Entity("MobID.MainGateway.Models.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("MobID.MainGateway.Models.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2025, 5, 25, 23, 56, 19, 806, DateTimeKind.Utc).AddTicks(7819),
                            Description = "Administrator role",
                            Name = "Admin",
                            UpdatedAt = new DateTime(2025, 5, 25, 23, 56, 19, 806, DateTimeKind.Utc).AddTicks(7820)
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2025, 5, 25, 23, 56, 19, 806, DateTimeKind.Utc).AddTicks(7824),
                            Description = "Organization user role",
                            Name = "OrgUser",
                            UpdatedAt = new DateTime(2025, 5, 25, 23, 56, 19, 806, DateTimeKind.Utc).AddTicks(7824)
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2025, 5, 25, 23, 56, 19, 806, DateTimeKind.Utc).AddTicks(7827),
                            Description = "Simple user role",
                            Name = "SimpleUser",
                            UpdatedAt = new DateTime(2025, 5, 25, 23, 56, 19, 806, DateTimeKind.Utc).AddTicks(7828)
                        });
                });

            modelBuilder.Entity("MobID.MainGateway.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            CreatedAt = new DateTime(2025, 5, 25, 23, 56, 19, 958, DateTimeKind.Utc).AddTicks(4177),
                            Email = "admin@example.com",
                            PasswordHash = "$2a$11$TeWi.xa.fTsRHN6vBzULU.jh.IISg2WUdvHizvv7tmYoCwNipk8Wi",
                            UpdatedAt = new DateTime(2025, 5, 25, 23, 56, 19, 958, DateTimeKind.Utc).AddTicks(4178),
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreatedAt = new DateTime(2025, 5, 25, 23, 56, 19, 958, DateTimeKind.Utc).AddTicks(4183),
                            Email = "user@example.com",
                            PasswordHash = "$2a$11$TeWi.xa.fTsRHN6vBzULU.jh.IISg2WUdvHizvv7tmYoCwNipk8Wi",
                            UpdatedAt = new DateTime(2025, 5, 25, 23, 56, 19, 958, DateTimeKind.Utc).AddTicks(4183),
                            Username = "user"
                        });
                });

            modelBuilder.Entity("MobID.MainGateway.Models.Entities.UserAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccessId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccessId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAccesses");
                });

            modelBuilder.Entity("MobID.MainGateway.Models.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            RoleId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2025, 5, 25, 23, 56, 19, 958, DateTimeKind.Utc).AddTicks(4323),
                            Id = new Guid("11111111-2222-3333-4444-555555555555"),
                            IsActive = true,
                            UpdatedAt = new DateTime(2025, 5, 25, 23, 56, 19, 958, DateTimeKind.Utc).AddTicks(4324)
                        },
                        new
                        {
                            UserId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            RoleId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2025, 5, 25, 23, 56, 19, 958, DateTimeKind.Utc).AddTicks(4335),
                            Id = new Guid("66666666-7777-8888-9999-aaaaaaaaaaaa"),
                            IsActive = true,
                            UpdatedAt = new DateTime(2025, 5, 25, 23, 56, 19, 958, DateTimeKind.Utc).AddTicks(4335)
                        });
                });

            modelBuilder.Entity("Scan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccessId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("QrCodeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ScannedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ScannedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccessId");

                    b.HasIndex("QrCodeId");

                    b.HasIndex("ScannedById");

                    b.ToTable("Scans");
                });

            modelBuilder.Entity("MobID.MainGateway.Models.Entities.Access", b =>
                {
                    b.HasOne("MobID.MainGateway.Models.Entities.AccessType", "AccessType")
                        .WithMany("Accesses")
                        .HasForeignKey("AccessTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MobID.MainGateway.Models.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MobID.MainGateway.Models.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccessType");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("MobID.MainGateway.Models.Entities.Organization", b =>
                {
                    b.HasOne("MobID.MainGateway.Models.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("MobID.MainGateway.Models.Entities.OrganizationAccessShare", b =>
                {
                    b.HasOne("MobID.MainGateway.Models.Entities.Access", "Access")
                        .WithMany("OrganizationAccessShares")
                        .HasForeignKey("AccessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MobID.MainGateway.Models.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MobID.MainGateway.Models.Entities.Organization", "SourceOrganization")
                        .WithMany()
                        .HasForeignKey("SourceOrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MobID.MainGateway.Models.Entities.Organization", "TargetOrganization")
                        .WithMany("OrganizationAccessShares")
                        .HasForeignKey("TargetOrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Access");

                    b.Navigation("Creator");

                    b.Navigation("SourceOrganization");

                    b.Navigation("TargetOrganization");
                });

            modelBuilder.Entity("MobID.MainGateway.Models.Entities.OrganizationUser", b =>
                {
                    b.HasOne("MobID.MainGateway.Models.Entities.Organization", "Organization")
                        .WithMany("OrganizationUsers")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MobID.MainGateway.Models.Entities.User", "User")
                        .WithMany("OrganizationUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MobID.MainGateway.Models.Entities.QrCode", b =>
                {
                    b.HasOne("MobID.MainGateway.Models.Entities.Access", "Access")
                        .WithMany("QrCodes")
                        .HasForeignKey("AccessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Access");
                });

            modelBuilder.Entity("MobID.MainGateway.Models.Entities.RefreshToken", b =>
                {
                    b.HasOne("MobID.MainGateway.Models.Entities.User", "User")
                        .WithOne("RefreshToken")
                        .HasForeignKey("MobID.MainGateway.Models.Entities.RefreshToken", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MobID.MainGateway.Models.Entities.UserAccess", b =>
                {
                    b.HasOne("MobID.MainGateway.Models.Entities.Access", "Access")
                        .WithMany("UserAccesses")
                        .HasForeignKey("AccessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MobID.MainGateway.Models.Entities.User", "User")
                        .WithMany("UserAccesses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Access");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MobID.MainGateway.Models.Entities.UserRole", b =>
                {
                    b.HasOne("MobID.MainGateway.Models.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MobID.MainGateway.Models.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Scan", b =>
                {
                    b.HasOne("MobID.MainGateway.Models.Entities.Access", null)
                        .WithMany("Scans")
                        .HasForeignKey("AccessId");

                    b.HasOne("MobID.MainGateway.Models.Entities.QrCode", "QrCode")
                        .WithMany("Scans")
                        .HasForeignKey("QrCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MobID.MainGateway.Models.Entities.User", "ScannedBy")
                        .WithMany()
                        .HasForeignKey("ScannedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QrCode");

                    b.Navigation("ScannedBy");
                });

            modelBuilder.Entity("MobID.MainGateway.Models.Entities.Access", b =>
                {
                    b.Navigation("OrganizationAccessShares");

                    b.Navigation("QrCodes");

                    b.Navigation("Scans");

                    b.Navigation("UserAccesses");
                });

            modelBuilder.Entity("MobID.MainGateway.Models.Entities.AccessType", b =>
                {
                    b.Navigation("Accesses");
                });

            modelBuilder.Entity("MobID.MainGateway.Models.Entities.Organization", b =>
                {
                    b.Navigation("OrganizationAccessShares");

                    b.Navigation("OrganizationUsers");
                });

            modelBuilder.Entity("MobID.MainGateway.Models.Entities.QrCode", b =>
                {
                    b.Navigation("Scans");
                });

            modelBuilder.Entity("MobID.MainGateway.Models.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("MobID.MainGateway.Models.Entities.User", b =>
                {
                    b.Navigation("OrganizationUsers");

                    b.Navigation("RefreshToken")
                        .IsRequired();

                    b.Navigation("UserAccesses");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
